[package]
name = "sycl-rs"
version = "0.1.0"
description = "Rust bindings for SYCL"
documentation = "https://docs.rs/sycl-rs"
keywords = ["oneapi", "sycl", "gpu"]
categories = [
    "api-bindings",
    "hardware-support",
    "memory-management",
    "science"]
publish = ["crates-io"]

# Inherit settings from the root workspace
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
allocator-api2 = "0.4.0"
bytemuck = "1.25.1"
cxx = "1.0.194"
sycl-rs-sys = { version = "0.1.0", path = "../sycl-rs-sys" }
sycl-rs-derive = { version = "0.1.0", path = "../sycl-rs-derive" }
pin-project = "1.1.13"
thiserror = "2.0.18"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt", "rt-multi-thread"] }
