[package]
name = "sycl-rs-derive"
version = "0.1.0"
description = "Internal procedural macros for sycl-rs"
publish = ["crates-io"]

# Inherit settings from the root workspace
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.3"
